### ISSUE TITLE
Definir as funcionalidades da aplicação

### ISSUE THREAD

**Issue by profjosereginaldo** [profjosereginaldo/pifrontend#1]

**Comment by profjosereginaldo** [comment]
Acho que devemos implementar essas funcionalides
- login
- perfil
- cadatro

**Comment by pedro-git-projects** [comment]
Concordo

**Comment by pedro-git-projects** [comment]
> Acho que devemos implementar essas funcionalides
> 
>     * login
> 
>     * perfil
> 
>     * cadatro

Concordo
